events {}

http {

  server {
    listen 80;
    server_name pokespheara.localhost;

    location / {
      proxy_pass http://pokespheara:80;
    }
  }
  
  server {
    listen 80;
    server_name eldenring.localhost;

    location / {
      proxy_pass http://eldenring:80;
    }
  }
  
  server {
    listen 80;
    server_name archive.localhost;

    location / {
      proxy_pass http://archive:80;
    }
  }
}